name: Deploy to Server
on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lab1 .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/lab1
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/lab1
          docker stop lab1 || true
          docker rm lab1 || true
          docker run -d --name lab1 -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/lab1